### ISSUE TITLE
blacklist-filter dont ignore files without extension

### ISSUE THREAD

**Issue by mariolorenz** [OXID-eSales/oxideshop_composer_plugin#10]
I'm trying to ignore a directory structure with developer files in my module.
In the composer.json of my module, i exclude the "resources"-path. Among other things, the path contains a complete node installation (resources\node_modules\...)

```
"extra": {
	"oxideshop": {
		"blacklist-filter": [
			"resources/**/*"
		],
		"target-directory": "myvendor/mymodule"
	}
},
```

For developing i install this modul in my shop-composer-file via "type": "path"
```
"repositories": [
	{"type": "path", "url": "../LocalPathToTheModule"},
]
```

After "composer install --no-dev" i found in the shop-sources, this path-structure with some files:
shoproot/source/modules/myvendor/mymodule/resources/node_modules/...
It is interesting that it is not the full directory structure, only the paths contains files without extension (LICENSE, AUTHORS, MakeFile etc.).

Can you reproduce and fix it?

PS:
I tried too
```
"resources/**/*",
"resources/**/*.",
"resources/**/*.*"
```
it doesent matter ...

**Comment by Sieg** [comment]
Hi, it is very strange, are you sure those files were not Alone in the original directories? I was not able to reproduce the problem locally:

* created 4 level directories in some local repository
* added the repository to blacklist-filter as "firstlevel/\*\*/\*"
* put README file into the deepest level
* required the local repository (tried in dev and no-dev)
* repository contents copied without the directory (so cannot reproduce)

Some questions to you:

- What is your system configuration? Do you use OXID VM?
- Have you used the create-project functionality to install the eshop, or any other way?
- Could you please share some example directory on github, which will not work for you, so we could try the exact package?

Little idea to check - Try to register your local package to be taken without symlink, it may be the problem for globmatcher to calculate right patchs, but still its strange it works with other files:

    "repositories": {
        "oxid-esales/example-module": {
            "type": "path",
            "url": "/var/www/oxideshop/tmp/example",
            "options": {
                "symlink": false
            }
        }
    }

Please patch the GlobMatcher locally (add echo $relativePatch), to check what files the iterator sees during copying in composer plugin so we could continue: https://github.com/OXID-eSales/oxideshop_composer_plugin/blob/master/src/Utilities/CopyFileManager/GlobMatcher/GlobMatcher.php#L29

**Comment by mariolorenz** [comment]
Hi,
i have a WAMP-System and i use the recommended OXID-composer-Installation.
Your idea works fine!
i´ve added  "options": {"symlink": false}
and now it works as I expected.
Please add your tipp to the oxid-module-documentation. Maybe an other programmer has the same issue.
Thanks!
