### ISSUE TITLE
Force answer for development version to rewrite theme/module

### ISSUE THREAD

**Issue by stasiukaitis-saulius** [OXID-eSales/oxideshop_composer_plugin#2]
It's a bit disturbing to have a question if update module/theme on each composer update. It would be better to have possibility to force to override or not all modules/themes.

**Comment by Sieg** [comment]
Hello @stasiukaitis-saulius, i have moved your issue to our Bugtracker: https://bugs.oxid-esales.com/view.php?id=6867. Please, follow it there, to see a progress.
