### ISSUE TITLE
TODO: Extract VfsFileStructureOperator.php into component

### ISSUE THREAD

**Issue by rezonanc-oxid** [OXID-eSales/oxideshop_composer_plugin#7]
Extracting `VfsFileStructureOperator.php` might be beneficial for other components which inside the tests are already using `VfsStream`.

Source for the class to be extracted: https://github.com/OXID-eSales/oxideshop_composer_plugin/blob/c6c82ce2d715e7024cf044d77dda2ab1c9734c0a/src/Utilities/VfsFileStructureOperator.php

Possible ways to extract:
* Make separate component
* Integrate with [testing_library](https://github.com/OXID-eSales/testing_library)

**Comment by Sieg** [comment]
Hello @rezonanc-oxid, i have moved this issue to our Bugtrack to have everything in one place. Please check the issue at: https://bugs.oxid-esales.com/view.php?id=6868 to see progress.
