### ISSUE TITLE
Run shop in different folder than "source".

### ISSUE THREAD

**Issue by proggeramlug** [OXID-eSales/oxideshop_composer_plugin#8]
It should be possible to specify a different name than "source" for SHOP_SOURCE_DIRECTORY.

If a shop should run in a subfolder the folder name will differ from "source".

**Comment by Sieg** [comment]
Hello @proggeramlug, I have moved your issue to our Bugtracker: https://bugs.oxid-esales.com/view.php?id=6866. Please follow the progress there.
