### ISSUE TITLE
Setup directory is not completely empty after running composer update

### ISSUE THREAD

**Issue by BenjaminJoerger** [OXID-eSales/oxideshop_composer_plugin#9]
There exists a regexp which avoids that setup files are not copied again to the source folder when running composer update. Saldy the regexp does not work correct. 
- Files in Setup/* are not copied
- Folders and their content in Setup/ ARE copied

**Comment by Sieg** [comment]
Hello @BenjaminJoerger, i have moved your issue to bugtracker: https://bugs.oxid-esales.com/view.php?id=6865, please follow the progress there.
